// Export all components
export * from './components'

export { datePresets } from './composables/useCalendarDates'
// Composables
export { formatLabel, installColorffyConfig, useColorffyConfig, useLabels } from './composables/useColorffyConfig'
export { useDateUtils } from './composables/useDateUtils'
export { useTextUtils } from './composables/useTextUtils'
export { useToast } from './composables/useToast'

// Global Registration - Export both as named and default
export { default as ColorffyUI } from './plugin'
export { default } from './plugin'

// Types
export type * from './types/accordion'
export type * from './types/alert'
export type * from './types/avatar'
export type * from './types/badge'
export type * from './types/breadcrumb'
export type * from './types/button'
export type * from './types/calendar'
export type * from './types/card'
export type * from './types/chip'
export type * from './types/config'
export type * from './types/datatable'
export type * from './types/dialog'
export type * from './types/divider'
export type * from './types/icon'
export type * from './types/input'
export type * from './types/layout'
export type * from './types/list'
export type * from './types/navbar'
export type * from './types/navigation'
export type * from './types/pagination'
export type * from './types/popover'
export type * from './types/progress'
export type * from './types/shared'
export type * from './types/sidebar'
export type * from './types/stepper'
export type * from './types/timeline'
export type * from './types/toast'
export type * from './types/tooltip'
